services:
  # Banco de dados exclusivo do Keycloak (Boa pr√°tica de isolamento)
  keycloak-db:
    image: postgres:17
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - gym-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: gym_keycloak
    command: start-dev # Modo de desenvolvimento (permite HTTP)
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}        # Login do Admin Geral
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD} # Senha do Admin Geral
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - gym-net

  app-db:
    image: postgres:17
    container_name: application_postgres
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - application_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gym-net

volumes:
  keycloak_data:
  application_data:

networks:
  gym-net:
    driver: bridge